name: ofdiff
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pytorch==2.5.1
  - torchvision==0.20.1
  - pytorch-cuda=12.1
  - pip:
      - gradio==5.29.0
      - albumentations==2.0.7
      - opencv-contrib-python==4.11.0.86
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - pytorch-lightning==2.5.1.post0
      - omegaconf==2.3.0
      - test-tube>=0.7.5
      - streamlit==1.12.1
      - einops==0.8.1
      - transformers==4.52.4
      - webdataset==0.2.111
      - open_clip_torch==2.32.0
      - invisible-watermark>=0.1.5
      - streamlit-drawable-canvas==0.8.0
      - torchmetrics==1.7.1
      - timm==1.0.15
      - addict==2.4.0
      - yapf==0.32.0
      - prettytable==3.6.0
      - safetensors==0.5.3
      - basicsr==1.4.2
      - xformers==0.0.29.post1
      - deepspeed==0.16.9